"""
Trade journal analyzer.

Reads outputs/trade_log.csv (generated by run.py backtest) and runs
the AI journal agent to find patterns, mistakes, and improvements.

Can also analyze a single trade interactively.

Usage:
    python run_journal.py                     # analyze all trades in trade_log.csv
    python run_journal.py --single            # walk through one trade interactively
    python run_journal.py --csv path/to/log.csv
"""

import argparse
import os
import sys
import logging
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.WARNING)

GREEN  = "\033[92m"
RED    = "\033[91m"
YELLOW = "\033[93m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"
RESET  = "\033[0m"


def load_trades(csv_path: str) -> list:
    try:
        import pandas as pd
        df = pd.read_csv(csv_path)
        return df.to_dict("records")
    except FileNotFoundError:
        print(f"{RED}File not found: {csv_path}{RESET}")
        print("Run  python run.py  first to generate trade_log.csv")
        sys.exit(1)


def print_journal_result(result: dict):
    print(f"\n{BOLD}── AI Journal Analysis ───────────────────────────────{RESET}")

    if result.get("mistakes"):
        print(f"\n{RED}Mistakes Found:{RESET}")
        for i, m in enumerate(result["mistakes"], 1):
            print(f"  {i}. {m}")

    if result.get("patterns"):
        print(f"\n{CYAN}Patterns:{RESET}")
        for p in result["patterns"]:
            print(f"  • {p}")

    if result.get("improvements"):
        print(f"\n{GREEN}Improvements:{RESET}")
        for i, imp in enumerate(result["improvements"], 1):
            print(f"  {i}. {imp}")

    if result.get("verdict"):
        print(f"\n{BOLD}Verdict:{RESET} {result['verdict']}")

    print(f"\n{BOLD}── Raw Output ────────────────────────────────────────{RESET}")
    print(result.get("raw", ""))


def analyze_all(csv_path: str):
    trades = load_trades(csv_path)
    print(f"\n{BOLD}{'═'*55}{RESET}")
    print(f"{BOLD}   TRADE JOURNAL ANALYSIS  ({len(trades)} trades){RESET}")
    print(f"{BOLD}{'═'*55}{RESET}\n")

    from trading_system.agents.journal import JournalAgent
    agent = JournalAgent()
    print("Running AI analysis...")
    result = agent.analyze_trades(trades)
    print_journal_result(result)


def analyze_single():
    print(f"\n{BOLD}── Single Trade Journal ──────────────────────────────{RESET}")
    print("Enter trade details:\n")

    trade = {
        "symbol":       input("Symbol (e.g. RELIANCE): ").strip().upper(),
        "entry_date":   input("Entry date (YYYY-MM-DD): ").strip(),
        "exit_date":    input("Exit date  (YYYY-MM-DD): ").strip(),
        "entry_price":  float(input("Entry price: ") or 0),
        "exit_price":   float(input("Exit price:  ") or 0),
        "holding_days": input("Holding days: ").strip(),
        "exit_reason":  input("Exit reason (stop_loss / profit_target / signal_exit): ").strip(),
    }
    pnl = (trade["exit_price"] - trade["entry_price"])
    ret = (pnl / trade["entry_price"] * 100) if trade["entry_price"] else 0
    trade["net_pnl"]    = pnl
    trade["return_pct"] = ret

    why    = input("\nWhy did you take this trade? ").strip()
    feeling = input("How did it feel when it closed? ").strip()

    from trading_system.agents.journal import JournalAgent
    agent  = JournalAgent()
    print("\nAnalyzing...\n")
    result = agent.analyze_single_trade(trade, why, feeling)
    print(result.get("raw", ""))


def main():
    if not os.environ.get("GROQ_API_KEY"):
        print(f"\n{RED}ERROR: GROQ_API_KEY not set in .env{RESET}")
        sys.exit(1)

    parser = argparse.ArgumentParser(description="AI Trade Journal Analyzer")
    parser.add_argument("--single", action="store_true", help="Analyze a single trade interactively")
    parser.add_argument("--csv", default="outputs/trade_log.csv", help="Path to trade_log.csv")
    args = parser.parse_args()

    if args.single:
        analyze_single()
    else:
        analyze_all(args.csv)


if __name__ == "__main__":
    main()
