"""
Nifty 50 stock universe with display metadata.
All 50 constituents as of 2025 — update quarterly.
"""

NIFTY50: list[dict] = [
    {"symbol": "RELIANCE.NS",    "name": "Reliance Industries",  "sector": "Energy"},
    {"symbol": "TCS.NS",         "name": "Tata Consultancy",     "sector": "IT"},
    {"symbol": "HDFCBANK.NS",    "name": "HDFC Bank",            "sector": "Banking"},
    {"symbol": "BHARTIARTL.NS",  "name": "Bharti Airtel",        "sector": "Telecom"},
    {"symbol": "ICICIBANK.NS",   "name": "ICICI Bank",           "sector": "Banking"},
    {"symbol": "INFOSYS.NS",     "name": "Infosys",              "sector": "IT"},
    {"symbol": "SBIN.NS",        "name": "State Bank of India",  "sector": "Banking"},
    {"symbol": "HINDUNILVR.NS",  "name": "HUL",                  "sector": "FMCG"},
    {"symbol": "ITC.NS",         "name": "ITC",                  "sector": "FMCG"},
    {"symbol": "BAJFINANCE.NS",  "name": "Bajaj Finance",        "sector": "NBFC"},
    {"symbol": "WIPRO.NS",       "name": "Wipro",                "sector": "IT"},
    {"symbol": "KOTAKBANK.NS",   "name": "Kotak Mahindra Bank",  "sector": "Banking"},
    {"symbol": "LT.NS",          "name": "Larsen & Toubro",      "sector": "Infra"},
    {"symbol": "ASIANPAINT.NS",  "name": "Asian Paints",         "sector": "Consumer"},
    {"symbol": "AXISBANK.NS",    "name": "Axis Bank",            "sector": "Banking"},
    {"symbol": "MARUTI.NS",      "name": "Maruti Suzuki",        "sector": "Auto"},
    {"symbol": "TATAMOTORS.NS",  "name": "Tata Motors",          "sector": "Auto"},
    {"symbol": "SUNPHARMA.NS",   "name": "Sun Pharma",           "sector": "Pharma"},
    {"symbol": "TITAN.NS",       "name": "Titan Company",        "sector": "Consumer"},
    {"symbol": "ADANIPORTS.NS",  "name": "Adani Ports",          "sector": "Infra"},
    {"symbol": "ULTRACEMCO.NS",  "name": "UltraTech Cement",     "sector": "Cement"},
    {"symbol": "NESTLEIND.NS",   "name": "Nestle India",         "sector": "FMCG"},
    {"symbol": "M&M.NS",         "name": "Mahindra & Mahindra",  "sector": "Auto"},
    {"symbol": "NTPC.NS",        "name": "NTPC",                 "sector": "Power"},
    {"symbol": "POWERGRID.NS",   "name": "Power Grid",           "sector": "Power"},
    {"symbol": "HCLTECH.NS",     "name": "HCL Technologies",     "sector": "IT"},
    {"symbol": "BAJAJFINSV.NS",  "name": "Bajaj Finserv",        "sector": "NBFC"},
    {"symbol": "TATASTEEL.NS",   "name": "Tata Steel",           "sector": "Metals"},
    {"symbol": "JSWSTEEL.NS",    "name": "JSW Steel",            "sector": "Metals"},
    {"symbol": "ONGC.NS",        "name": "ONGC",                 "sector": "Energy"},
    {"symbol": "COALINDIA.NS",   "name": "Coal India",           "sector": "Metals"},
    {"symbol": "TECHM.NS",       "name": "Tech Mahindra",        "sector": "IT"},
    {"symbol": "HINDALCO.NS",    "name": "Hindalco",             "sector": "Metals"},
    {"symbol": "DRREDDY.NS",     "name": "Dr. Reddy's",          "sector": "Pharma"},
    {"symbol": "CIPLA.NS",       "name": "Cipla",                "sector": "Pharma"},
    {"symbol": "APOLLOHOSP.NS",  "name": "Apollo Hospitals",     "sector": "Healthcare"},
    {"symbol": "TATACONSUM.NS",  "name": "Tata Consumer",        "sector": "FMCG"},
    {"symbol": "DIVISLAB.NS",    "name": "Divi's Labs",          "sector": "Pharma"},
    {"symbol": "GRASIM.NS",      "name": "Grasim Industries",    "sector": "Cement"},
    {"symbol": "EICHERMOT.NS",   "name": "Eicher Motors",        "sector": "Auto"},
    {"symbol": "HEROMOTOCO.NS",  "name": "Hero MotoCorp",        "sector": "Auto"},
    {"symbol": "BPCL.NS",        "name": "BPCL",                 "sector": "Energy"},
    {"symbol": "INDUSINDBK.NS",  "name": "IndusInd Bank",        "sector": "Banking"},
    {"symbol": "ADANIENT.NS",    "name": "Adani Enterprises",    "sector": "Conglomerate"},
    {"symbol": "SHRIRAMFIN.NS",  "name": "Shriram Finance",      "sector": "NBFC"},
    {"symbol": "BAJAJ-AUTO.NS",  "name": "Bajaj Auto",           "sector": "Auto"},
    {"symbol": "BRITANNIA.NS",   "name": "Britannia",            "sector": "FMCG"},
    {"symbol": "SBILIFE.NS",     "name": "SBI Life Insurance",   "sector": "Insurance"},
    {"symbol": "HDFCLIFE.NS",    "name": "HDFC Life",            "sector": "Insurance"},
    {"symbol": "BEL.NS",         "name": "Bharat Electronics",   "sector": "Defence"},
]

NIFTY50_SYMBOLS = [s["symbol"] for s in NIFTY50]
SYMBOL_META     = {s["symbol"]: s for s in NIFTY50}
